title: The Theorem Prover Museum
permalink:        /news/:year/:month/:day/:title/
url:                 http://theoremprover-museum.github.io
baseurl:             ''

# all the pagination
gems:
  - jekyll-paginate
paginate:            10
paginate_path:       "/news/page:num/"
blog_path:           "/news/"

# About/contact
author:
  name:              'Michael Kohlhase'
  url:                   http://kwarc.info/kohlhase
  email:               michael.kohlhase@fau.de
